### PR TITLE
Uploading progress bar

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
As discussed in #288 

https://user-images.githubusercontent.com/37152329/152943548-9b65eb36-8632-4e58-89db-623c947c6085.mp4

https://user-images.githubusercontent.com/37152329/152943559-151fd900-2bdf-4f80-8cca-6bc67adee00b.mp4

# Conflict

https://user-images.githubusercontent.com/37152329/152943623-b5c22e35-8768-458d-9fe9-cf34a10d8979.mp4

https://user-images.githubusercontent.com/37152329/152943660-58cf6563-c535-4e2a-8c86-6b6c404c4046.mp4

##
- Rearranged files in cfd0d0be593e6dd308777ad523d8287b6645e59b.
- Actual changes in 1bbb760586424e97a7fed629eaa3fe0140110302, and 1f97d0594e0c4334c660ba0ad65ddee1dce2f563.

### CODE REVIEW

**Comment by kasbah** [comment]
Very nice, could you get rid of the left side after upload?

**Comment by AbdulrhmnGhanem** [comment]
> get rid of the left side after upload

Please, explain it visually.

**Comment by kasbah** [comment]
Would make sense to get rid of this when the upload shows I think. It's not like you will suddenly change your mind and import/sync a repo while you are uploading. 

image

**Comment by AbdulrhmnGhanem** [comment]
What about disabling it? Removing it will cause layout shifts if we remove it or a sudden disappearance if we hide it.

**Comment by kasbah** [comment]
I don't think layout shift is a problem here. Think of it more like a new page. If it fails, go back to the old page otherwise go to the next page.

**Comment by AbdulrhmnGhanem** [comment]
OK I will try it.

**Comment by kasbah** [comment]
Converting this to draft to handle merge conflicts with #295. Feel free to mark as ready once that's merged.

**Comment by AbdulrhmnGhanem** [comment]
Please try it on https://abdo-dev.staging.kitspace.dev!

**Comment by kasbah** [comment]
Looks good!

**Comment by kasbah** [comment]
Merging since that branch is still being reviewed.

**Pull request merged**
