### PR TITLE
Improve routes

### LINKED ISSUE #69: Routes are a bit ugly right now
I'm not a big fan of the `/projects/mine` route and some of the other ones. @AbdulrhmnGhanem I remember you saying you aren't too fond of it either. Let's come up with something better. Here's a start:

- route: `/` 
Proxy to to `/search` but still appears as `/`. When someone enters a search it will change to `/search?q=`. 
- route: `/search`
Display all projects, from most recently updated. You can add a search query as a parameter: `/search?q=` 
- route  `/<user-name>`
Proxy to `/search?q=user:user-name` (or however it actually works in Gitea search). Still appears as `/<user-name>`.
- route `/<user-name>/<project-name>`. 
Proxy to `/projects/<user-name>/<project-name>` but appears as `/<user-name>/<project-name>`
- route `/projects/<user-name>/<project-name>`
The project page.

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
closes #69.

### CODE REVIEW

**Comment by kasbah** [comment]
Should this be a draft?

**Comment by AbdulrhmnGhanem** [comment]
- [x]  route: `/`
Proxy to to `/search` but still appears as `/`. When someone enters a search it will change to `/search?q=`.
- [x]  route: `/search`
Display all projects, from most recently updated. You can add a search query as a parameter: `/search?q=`
- [x]  route `/<user-name>`
Proxy to `/search?q=user:user-name` (or however it actually works in Gitea search). Still appears as `/<user-name>`.
- [x]  route `/<user-name>/<project-name>`.
Proxy to `/projects/<user-name>/<project-name>` but appears as `/<user-name>/<project-name>`
- [ ]  route `/projects/<user-name>/<project-name>`

What should be the replacement for `/mine`?

**Comment by kasbah** [comment]
I think it can just be `/<user-name>`.

**Comment by AbdulrhmnGhanem** [comment]
> route `/projects/<user-name>/<project-name>`
Is this still needed?

**Comment by kasbah** [comment]
No, not really. It's more of an implementation detail if it's needed or not. The important one is `/<user>/<project>`. I thought with the way Next works we might need to "alias" it.

**Pull request merged**
