### PR TITLE
Add version prefix to processor assets

### PR DESCRIPTION
**Pull request by kasbah**

### CODE REVIEW

**Comment by AbdulrhmnGhanem** [comment]
I think you need to update the following line too, right?

https://github.com/kitspace/kitspace-v2/blob/958f200ca567c4438f6b0cd9481f1276a6aa4916/processor/src/queues.ts#L130

**Review by AbdulrhmnGhanem — CHANGES_REQUESTED** [review]
I think you need to update the following line too, right?

https://github.com/kitspace/kitspace-v2/blob/958f200ca567c4438f6b0cd9481f1276a6aa4916/processor/src/queues.ts#L130

**Comment by kasbah** [comment]
It is updated already on this branch. You are linking to master. 

https://github.com/kitspace/kitspace-v2/pull/586/files#diff-cb0fe09747ccf9d7eec1769347ea30d51af5836f25b3cfb519e7e746efe4af49R130-R136

**Comment by AbdulrhmnGhanem** [comment]
My bad!

**Pull request merged**
