### PR TITLE
Fix blinking of logo component on Firefox

### LINKED ISSUE #266: Logo re-rendering for no reason
When you navigate around the logo blinks in and out. No idea why, it should just be staying in place.

### PR DESCRIPTION
**Pull request by kasbah**
I think this fixes #266. I'm still confused about this one though, about the ref passing etc. not sure what it was for at all. I never saw any warnings about it. Maybe it was fixed?

### CODE REVIEW

**Comment by kasbah** [comment]
Ah found the docs about it: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component (that should have been in the comment!)

Anyway, it doesn't seem to fix #266

**Comment by AbdulrhmnGhanem** [comment]
The navbar height has increased, is it intentional?

**Comment by kasbah** [comment]
Not really, but by a pixel or something? Seems fine... nav bar has some layout shift issues anyway so will need to take a close look at the heights of things at some point.

**Comment by kasbah** [comment]
@AbdulrhmnGhanem can you update the snapshots for now please? (Though we need a better way of doing this as mentioned in #290.)

**Pull request merged**
