### PR TITLE
Upgrade to KiCad 7

### PR DESCRIPTION
**Pull request by kasbah**
- Upgrade our scripts to KiCad 7
- Upgrade IBOM for compatibility, IBOM has native Eagle support now so we no longer need to convert those to KiCad

### CODE REVIEW

**Comment by kasbah** [comment]
Any improvements on this from porting it to EDeA?

**Comment by AbdulrhmnGhanem** [comment]
I added styles and made XML parsing safer, do you want to port that here?

**Comment by kasbah** [comment]
Styles, I think not because I'd like to set them from the outside so they can be switched out.

Safer, sure, but it's not a priority since the SVG/XML is generated on our servers from KiCad.

Guess is good to merge then?

**Comment by AbdulrhmnGhanem** [comment]
Did you check that IBOM is working as expected on importing a new project?  if yes, then it's OK to merge.

**Pull request merged**
