### PR TITLE
Configure CDN

### PR DESCRIPTION
**Pull request by kasbah**
I went for Bunny CDN. Mostly bypassing NextJS `Image` optimization to route the requests to the CDN since we don't have that much to optimize anyway, going to the CDN seems more important.

### CODE REVIEW

**Comment by kasbah** [comment]
Seems to be working and I've added CDN "pull zones" for `master` and `abdo-dev` too.

**Comment by AbdulrhmnGhanem** [comment]
I am getting 403 for all images 

image

**Comment by kasbah** [comment]
Why are you looking at kaspar-dev? I'm trying something out over there.

**Comment by AbdulrhmnGhanem** [comment]
I am trying to review the PR lol
is it deployed elsewhere?

**Comment by AbdulrhmnGhanem** [comment]
Ah I forgot about the review branch

**Review by AbdulrhmnGhanem — APPROVED** [review]

**Pull request merged**
