### PR TITLE
Use swc in frontend

### PR DESCRIPTION
**Pull request by kasbah**
I think it's time. Rebases #265 and gives the branch a better name.

### CODE REVIEW

**Comment by AbdulrhmnGhanem** [comment]
wdyr got supported by swc now https://github.com/vercel/next.js/issues/38502

**Comment by kasbah** [comment]
Ah, good to know. Let's add it when we need it on another PR?

**Comment by AbdulrhmnGhanem** [comment]
And jsx styles work out of the box now, great!

**Review by AbdulrhmnGhanem — APPROVED** [review]

**Comment by kasbah** [comment]
We don't seem to actually using styled-jsx. Maybe I should have just removed it?

**Comment by kasbah** [comment]
Ah we are using it in Readme.jsx, but it's `global` anyway? Could we just use .module.scss like the rest?

**Comment by AbdulrhmnGhanem** [comment]
We are

image
image

https://github.com/kitspace/kitspace-v2/blob/2f27987f200e0441f5ee6a0972167d65049be83d/frontend/src/components/Board/Readme.jsx#L10-L66

and for the mobile nav bar too.

**Comment by kasbah** [comment]
Can you remember why we didn't use module.scss for these though?

**Comment by AbdulrhmnGhanem** [comment]
#269

**Pull request merged**
