### PR TITLE
Fix e2e.

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**

### CODE REVIEW

**Comment by kasbah** [comment]
Not sure why the publish-docker-images isn't running on this now.

**Comment by AbdulrhmnGhanem** [comment]
Me too!

**Comment by kasbah** [comment]
Maybe because of the merges? Changing it to just `on: [push]` as I did on #92 might make this less confusing. 

This PR seems to be just the update to Gitea which you already pushed to master, is that intentional?

**Comment by AbdulrhmnGhanem** [comment]
It had a merge conflict so I pushed it to master, I think this can be closed.

**Comment by kasbah** [comment]
Can you look at why updateProject.spec.js  is failing?

https://github.com/kitspace/kitspace-v2/runs/2245905298

**Comment by AbdulrhmnGhanem** [comment]
Fix it here https://github.com/kitspace/kitspace-v2/pull/93/commits/263fbddc543da8d6eed2f30862d3eecd0756e0ba.

**Pull request closed without merging**
